name: flutter_win_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluent_ui: ^3.12.0
  system_theme: ^2.0.0
  flutter_acrylic: ^1.0.0+2
  provider: ^6.0.3
  url_launcher: ^6.1.4
  url_strategy: ^0.2.0
  window_manager: ^0.2.5
  fluentui_system_icons: ^1.1.173

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
